In [5]:
import json
import torch
import os

In [18]:
text_path = os.path.join('mydata','valdep.json')

In [19]:
with open(text_path) as f:
    dataset = json.load(f)

In [20]:
for i in dataset:
    i


In [21]:
dataset[100][5]

{'chunk_cap': ['corollary',
  ':',
  'if',
  'your bladder',
  'is',
  'tiny',
  ',',
  'don',
  "'",
  't',
  'drink',
  'a huge bottle',
  'of',
  'water',
  'before',
  'getting',
  'on',
  'the plane',
  '.',
  '# traveltips',
  '#',
  'haiku',
  '#',
  'lol',
  '#',
  'funny'],
 'token_cap': ['corollary',
  ':',
  'if',
  'your',
  'bladder',
  'is',
  'tiny',
  ',',
  'don',
  "'",
  't',
  'drink',
  'a',
  'huge',
  'bottle',
  'of',
  'water',
  'before',
  'getting',
  'on',
  'the',
  'plane',
  '.',
  '#',
  'traveltips',
  '#',
  'haiku',
  '#',
  'lol',
  '#',
  'funny'],
 'token_dep': [[2, 5],
  [3, 4],
  [4, 5],
  [5, 11],
  [6, 5],
  [8, 11],
  [10, 11],
  [11, 0],
  [12, 14],
  [13, 14],
  [14, 11],
  [15, 14],
  [16, 15],
  [17, 11],
  [18, 17],
  [19, 18],
  [20, 21],
  [21, 19],
  [26, 30],
  [28, 30],
  [30, 24]],
 'chunk_dep': [[2, 4],
  [3, 4],
  [4, 10],
  [5, 4],
  [7, 10],
  [9, 10],
  [10, 0],
  [11, 10],
  [12, 11],
  [13, 12],
  [14, 10],
  [15, 14],
  [16

In [14]:
label = dataset[100][2]

In [40]:
text = dataset[100][5]

In [35]:
dataset[100][4]

'there are two men sitting in the back of a plane'

In [41]:
text["token_cap"]

['corollary',
 ':',
 'if',
 'your',
 'bladder',
 'is',
 'tiny',
 ',',
 'don',
 "'",
 't',
 'drink',
 'a',
 'huge',
 'bottle',
 'of',
 'water',
 'before',
 'getting',
 'on',
 'the',
 'plane',
 '.',
 '#',
 'traveltips',
 '#',
 'haiku',
 '#',
 'lol',
 '#',
 'funny']

In [30]:
dep = text["token_dep"]

In [31]:
dep

[[0, 2],
 [1, 2],
 [3, 4],
 [4, 2],
 [7, 2],
 [9, 7],
 [11, 7],
 [13, 11],
 [15, 13],
 [16, 2],
 [18, 2],
 [20, 18],
 [22, 20]]

In [42]:
test = 'Hello my name'
test2 = ["w", "sd"]

In [44]:
temp = test.split(' ')

In [45]:
temp + test2

['Hello', 'my', 'name', 'w', 'sd']

In [46]:
temp

['Hello', 'my', 'name']

In [1]:
arr1 = [i for i in range(10)]
arr2 = [i for i in range(10)]

In [2]:
test = [i+j for i,j in zip(arr1, arr2)]

In [3]:
test

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [6]:
data = torch.randn(3, 2, 4)

In [8]:
data

tensor([[[ 1.3407,  0.1952,  1.7156, -0.0125],
         [-0.0549, -0.1563, -0.1781, -0.4349]],

        [[-1.8228,  0.2858, -2.2024,  0.0674],
         [ 1.4483,  0.9149, -0.0555, -0.3191]],

        [[ 0.3889,  0.3774, -0.1527, -0.0858],
         [-0.2523,  1.4381,  0.1103,  1.6855]]])

In [16]:
torch.sum(data ,dim=1, keepdim=True)

tensor([[[ 1.2858,  0.0389,  1.5375, -0.4474]],

        [[-0.3745,  1.2006, -2.2579, -0.2518]],

        [[ 0.1367,  1.8155, -0.0424,  1.5997]]])

In [17]:
torch.sum(data ,dim=(1,2), keepdim=True)

tensor([[[ 2.4148]],

        [[-1.6836]],

        [[ 3.5095]]])