In [5]:
import json
import torch
import os

In [39]:
text_path = os.path.join('mydata','valdep.json')

In [40]:
with open(text_path) as f:
    dataset = json.load(f)

In [41]:
dataset[100][2]

1

In [14]:
label = dataset[100][2]

In [40]:
text = dataset[100][5]

In [35]:
dataset[100][4]

'there are two men sitting in the back of a plane'

In [41]:
text["token_cap"]

['corollary',
 ':',
 'if',
 'your',
 'bladder',
 'is',
 'tiny',
 ',',
 'don',
 "'",
 't',
 'drink',
 'a',
 'huge',
 'bottle',
 'of',
 'water',
 'before',
 'getting',
 'on',
 'the',
 'plane',
 '.',
 '#',
 'traveltips',
 '#',
 'haiku',
 '#',
 'lol',
 '#',
 'funny']

In [30]:
dep = text["token_dep"]

In [31]:
dep

[[0, 2],
 [1, 2],
 [3, 4],
 [4, 2],
 [7, 2],
 [9, 7],
 [11, 7],
 [13, 11],
 [15, 13],
 [16, 2],
 [18, 2],
 [20, 18],
 [22, 20]]

In [42]:
test = 'Hello my name'
test2 = ["w", "sd"]

In [44]:
temp = test.split(' ')

In [45]:
temp + test2

['Hello', 'my', 'name', 'w', 'sd']

In [46]:
temp

['Hello', 'my', 'name']

In [1]:
arr1 = [i for i in range(10)]
arr2 = [i for i in range(10)]

In [2]:
test = [i+j for i,j in zip(arr1, arr2)]

In [3]:
test

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [6]:
data = torch.randn(3, 2, 4)

In [8]:
data

tensor([[[ 1.3407,  0.1952,  1.7156, -0.0125],
         [-0.0549, -0.1563, -0.1781, -0.4349]],

        [[-1.8228,  0.2858, -2.2024,  0.0674],
         [ 1.4483,  0.9149, -0.0555, -0.3191]],

        [[ 0.3889,  0.3774, -0.1527, -0.0858],
         [-0.2523,  1.4381,  0.1103,  1.6855]]])

In [16]:
torch.sum(data ,dim=1, keepdim=True)

tensor([[[ 1.2858,  0.0389,  1.5375, -0.4474]],

        [[-0.3745,  1.2006, -2.2579, -0.2518]],

        [[ 0.1367,  1.8155, -0.0424,  1.5997]]])

In [17]:
torch.sum(data ,dim=(1,2), keepdim=True)

tensor([[[ 2.4148]],

        [[-1.6836]],

        [[ 3.5095]]])

In [48]:
import torch

# 假设 input_tensor 的形状为 [batch_size, seq_length, embedding_dim]
# 假设 padding_mask 是一个形状与 input_tensor[:, :, 0] 相同的布尔张量

# 创建模拟的输入张量和填充掩码
input_tensor = torch.randn(2, 5, 10)  # 假设 batch_size=2, seq_length=5, embedding_dim=10
padding_mask = torch.tensor([[False, False, True, True, True],  # 填充掩码示例
                             [False, False, False, True, True]])

# # 将填充掩码转换为与输入张量相同的形状 # 在第1维度上添加一个维度，形状变为 [batch_size, 1, seq_length]

# 在计算注意力时应用填充掩码
# 假设我们使用了 PyTorch 的 nn.MultiheadAttention 模块
attention_layer = torch.nn.MultiheadAttention(embed_dim=10, num_heads=2)
output, _ = attention_layer(input_tensor, input_tensor, input_tensor, key_padding_mask=padding_mask)


TypeError: forward() got an unexpected keyword argument 'batch_first'

In [46]:
padding_mask.size()

torch.Size([2, 5])